project:
  type: book

title: "Minería de Datos"
author: "Alvaro Chirino Gutierrez"
date: "2026-01-01"
date-format: "YYYY"

book:
  #favicon: logo.png
  twitter-card: true
  site-url: https://example.com
  search: true
  repo-url: https://github.com/data_mining/
  downloads: [pdf]
  sharing: [twitter, facebook]
  cover-image: cover.png
  page-footer: 
    left: "Copyright 2026, Alvaro Chirino" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: bluesky 
        href: https://bsky.app/ 
  chapters:
    - index.qmd # Prefacio / Introducción general
    - part: "Parte I: Introducción y Fundamentos"
      chapters: 
        - fundamentos.qmd
        #- r.qmd
        #- scrape.qmd
    #- part: "Parte II: Modelado Múltiple"
     # chapters:
        #- analisis_exploratorio.qmd
        #- modelos.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      dark: darkly
      light: flatly